#!/bin/sh
if [ -f ~/src/github.com/KKPMW/dircolors-moonshine/dircolors.moonshine ]; then
  eval "$(dircolors ~/src/github.com/KKPMW/dircolors-moonshine/dircolors.moonshine)"
fi
eza -lg --git --color-scale --time-style long-iso "$@"
