resolver: lts-14.7

packages:
- .

extra-deps:
- http-client-0.6.4
- http-client-tls-0.3.5.3
- http-conduit-2.3.7.1
- http-types-0.12.3
- optparse-applicative-0.14.3.0
- regex-posix-0.95.2
- rio-0.1.12.0
- scalpel-core-0.6.0
